tweak bootstrap to accept long options

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -12,37 +12,43 @@ usage()
     download and install external dependencies.
 
     OPTIONS:
-       -O      Overwrite all existing content.
-       -B      Backup the existing content that would otherwise be 
-               replaced. 
-       -h      Show this message
+       -O | --overwrite-all      Overwrite all existing content.
+       -B | --backup-all         Backup the existing content that would otherwise be 
+                                 replaced. 
+       -S | --skip-all
+       -h | --help               Show this message
 EOF
 }
 
-overwrite_all=false
-backup_all=false
-skip_all=false
+OVERWRITE_ALL=false
+BACKUP_ALL=false
+SKIP_ALL=false
 
-while getopts “hOB” OPTION
-do
-     case $OPTION in
-         h)
-             usage
-             exit 1
-             ;;
-         B)
-             backup_all=true; 
-             ;;
-         O)
-             overwrite_all=true;
-             ;;
-         *)
-            usage
-            exit
+while [ "$1" != "" ]; do
+    PARAM=`echo $1 | awk -F= '{print $1}'`
+    VALUE=`echo $1 | awk -F= '{print $2}'`
+    case $PARAM in
+        -h | --help)
+            usage;
+            exit 1;
             ;;
-     esac
-     shift;
-done
+        -O | --OVERWRITE-all)
+            OVERWRITE_ALL=true;
+            ;;
+        -B | --BACKUP-all)
+            BACKUP_ALL=true;
+            ;;
+        -S | --SKIP-all)
+            SKIP_ALL=true;
+            ;;
+        *)
+            echo "ERROR: unknown parameter \"$PARAM\""
+            usage
+            exit 1
+            ;;
+    esac;
+    shift;
+done;
 
 DOTFILES_ROOT="`pwd`"
 
@@ -73,70 +79,67 @@ link_files () {
   success "linked $1 to $2"
 }
 
-install_dotfiles () {
-  info "installing dotfiles\n"
+info "installing dotfiles\n"
 
-  for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
-  do
-    dest="$HOME/.`basename \"${source%.*}\"`"
+for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`
+do
+  dest="$HOME/.`basename \"${source%.*}\"`"
 
-    if [ -f $dest ] || [ -d $dest ]
+  if [ -f $dest ] || [ -d $dest ]
+  then
+
+    OVERWRITE=false
+    BACKUP=false
+    SKIP=false
+
+    if [ "$OVERWRITE_ALL" == "false" ] && [ "$BACKUP_ALL" == "false" ] && [ "$SKIP_ALL" == "false" ]
     then
+      user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
+      read -n 1 action
 
-      overwrite=false
-      backup=false
-      skip=false
-
-      if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
-      then
-        user "File already exists: `basename $source`, what do you want to do? [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
-        read -n 1 action
-
-        case "$action" in
-          o )
-            overwrite=true;;
-          O )
-            overwrite_all=true;;
-          b )
-            backup=true;;
-          B )
-            backup_all=true;;
-          s )
-            skip=true;;
-          S )
-            skip_all=true;;
-          * )
-            ;;
-        esac
-      fi
-
-      if [ "$overwrite" == "true" ] || [ "$overwrite_all" == "true" ]
-      then
-        rm -rf $dest
-        success "removed $dest"
-      fi
-
-      if [ "$backup" == "true" ] || [ "$backup_all" == "true" ]
-      then
-        mv $dest $dest\.backup
-        success "moved $dest to $dest.backup"
-      fi
-
-      if [ "$skip" == "false" ] && [ "$skip_all" == "false" ]
-      then
-        link_files $source $dest
-      else
-        success "skipped $source"
-      fi
-
-    else
-      link_files $source $dest
+      case "$action" in
+        o )
+          OVERWRITE=true;;
+        O )
+          OVERWRITE_ALL=true;;
+        b )
+          BACKUP=true;;
+        B )
+          BACKUP_ALL=true;;
+        s )
+          SKIP=true;;
+        S )
+          SKIP_ALL=true;;
+        * )
+          ;;
+      esac
     fi
 
-  done
-}
+    if [ "$OVERWRITE" == "true" ] || [ "$OVERWRITE_ALL" == "true" ]
+    then
+      rm -rf $dest
+      success "removed $dest"
+    fi
 
-install_dotfiles
+    if [ "$BACKUP" == "true" ] || [ "$BACKUP_ALL" == "true" ]
+    then
+      mv $dest $dest\.backup
+      success "moved $dest to $dest.backup"
+    fi
+
+    if [ "$SKIP" == "false" ] && [ "$SKIP_ALL" == "false" ]
+    then
+      link_files $source $dest
+    else
+      success "skipped $source"
+    fi
+
+  else
+    link_files $source $dest
+  fi
+
+done
+
 
 # If we're on a Mac, let's install and setup homebrew.
 if [ "$(uname -s)" == "Darwin" ]
